/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.infinitic.loadTester.app

import com.xenomachina.argparser.ArgParser
import com.xenomachina.argparser.mainBody
import io.infinitic.loadTester.app.webserver.Http4kHttpServer
import io.infinitic.loadTester.launcher.Launcher
import io.infinitic.pulsar.InfiniticWorker
import org.slf4j.LoggerFactory
import setupPulsar

fun main(args: Array<String>) = mainBody {
    ArgParser(args).parseInto(::CliArgs).run {
        val logger = LoggerFactory.getLogger("AppKt.main")
        logger.info("Starting APP: $version - $configFilePath")
        Http4kHttpServer(port).startServer()
        logger.info("Webserver started")
        when (version) {
            Action.SetupPulsar -> setupPulsar(configFilePath)
            Action.Launcher -> Launcher.fromConfigFile(configFilePath).start()
            Action.Worker -> InfiniticWorker.fromConfigFile(configFilePath).start()
        }
    }
}
