/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.infinitic.loadTester.app

import com.xenomachina.argparser.ArgParser

enum class Version {
  SetupPulsar,
  Launcher,
  Workflow,
  Task,
}

class CliArgs(parser: ArgParser) {
  val version by parser.mapping(
      "--setup-pulsar" to Version.SetupPulsar,
      "--launcher" to Version.Launcher,
      "--workflow" to Version.Workflow,
      "--task" to Version.Task,
      help = "which version code to run")
  val port by parser.storing("-p", "--port", help = "port of the webserver") { toInt() }
  val configFilePath by parser.storing("-f", "--config-file", help = "path for config files")
}
