/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.infinitic.loadTester.app

import com.xenomachina.argparser.ArgParser

enum class Action {
  SetupPulsar,
  Launcher,
  Worker
}

class CliArgs(parser: ArgParser) {
  val version by parser.mapping(
      "--setup-pulsar" to Action.SetupPulsar,
      "--launcher" to Action.Launcher,
      "--worker" to Action.Worker,
      help = "which action code to run")
  val port by parser.storing("-p", "--port", help = "port of the webserver") { toInt() }
  val configFilePath by parser.storing("-f", "--config-file", help = "path for config files")
}
