/*
 * This file was generated by the Gradle 'init' task.
 */

plugins { id("io.infinitic.loadTester.kotlin-library-conventions") }

dependencies {
  // prometheus
  implementation(
      Io_infinitic_loadTester_kotlin_common_conventions_gradle.Libs.MicroMeter.prometheus)
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
  kotlinOptions { jvmTarget = JavaVersion.VERSION_1_8.toString() }
}

tasks.withType<JavaCompile> {
  sourceCompatibility = JavaVersion.VERSION_1_8.toString()
  targetCompatibility = JavaVersion.VERSION_1_8.toString()
}
