{
 "title": "Infinitic Workflow",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Workflows Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(workflow_launch_total[$__rate_interval]) ",
     "legendFormat": "Launched Workflows"
    },
    {
     "expr": "irate(workflow_start_total[$__rate_interval]) ",
     "legendFormat": "Started Workflows"
    },
    {
     "expr": "irate(workflow_end_total[$__rate_interval]) ",
     "legendFormat": "Finished Workflows"
    }
   ]
  },
  {
   "title": "Workflows execution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(workflow_launch_total[$__interval]) ",
     "legendFormat": "Launched Workflows"
    },
    {
     "expr": "increase(workflow_start_total[$__interval]) ",
     "legendFormat": "Started Workflows"
    },
    {
     "expr": "increase(workflow_end_total[$__interval]) ",
     "legendFormat": "Finished Workflows"
    }
   ]
  },
  {
   "title": "Supplier Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(supplierBBB_getProduct_total[$__rate_interval]) ",
     "legendFormat": "supplierBBB_getProduct"
    },
    {
     "expr": "irate(supplierBBB_reserveStock_total[$__rate_interval]) ",
     "legendFormat": "supplierBBB_reserveStock"
    },
    {
     "expr": "irate(supplierBBB_cancelStock_total[$__rate_interval]) ",
     "legendFormat": "supplierBBB_cancelStock"
    },
    {
     "expr": "irate(supplierAAA_getProduct_total[$__rate_interval]) ",
     "legendFormat": "supplierAAA_getProduct"
    },
    {
     "expr": "irate(supplierAAA_reserveStock_total[$__rate_interval]) ",
     "legendFormat": "supplierAAA_reserveStock"
    },
    {
     "expr": "irate(supplierAAA_cancelStock_total[$__rate_interval]) ",
     "legendFormat": "supplierAAA_cancelStock"
    }
   ]
  },
  {
   "title": "Supplier Exec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(supplierBBB_getProduct_total[$__rate_interval]) ",
     "legendFormat": "supplierBBB_getProduct"
    },
    {
     "expr": "increase(supplierBBB_reserveStock_total[$__rate_interval]) ",
     "legendFormat": "supplierBBB_reserveStock"
    },
    {
     "expr": "increase(supplierBBB_cancelStock_total[$__rate_interval]) ",
     "legendFormat": "supplierBBB_cancelStock"
    },
    {
     "expr": "increase(supplierAAA_getProduct_total[$__rate_interval]) ",
     "legendFormat": "supplierAAA_getProduct"
    },
    {
     "expr": "increase(supplierAAA_reserveStock_total[$__rate_interval]) ",
     "legendFormat": "supplierAAA_reserveStock"
    },
    {
     "expr": "increase(supplierAAA_cancelStock_total[$__rate_interval]) ",
     "legendFormat": "supplierAAA_cancelStock"
    }
   ]
  },
  {
   "title": "Workflow Counter values",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "workflow_launch_total", "legendFormat": "Launched Workflows" },
    { "expr": "workflow_start_total", "legendFormat": "Started Workflows" },
    { "expr": "workflow_end_total", "legendFormat": "Finished Workflows" }
   ]
  },
  {
   "title": "SupplierAAA Task Exec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(supplierAAA_getProduct_total[$__rate_interval]) ",
     "legendFormat": "supplierAAA_getProduct"
    },
    {
     "expr": "increase(supplierAAA_reserveStock_total[$__rate_interval]) ",
     "legendFormat": "supplierAAA_reserveStock"
    },
    {
     "expr": "increase(supplierAAA_cancelStock_total[$__rate_interval]) ",
     "legendFormat": "supplierAAA_cancelStock"
    }
   ]
  }
 ]
}