# my global config
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
# - "alert.rules"
# - "first.rules"
# - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090','node-exporter:9100','cadvisor:8080']
- job_name: 'pulsar'
  scrape_interval: 5s
  static_configs:
  - targets: ['pulsar-standalone:8080']
- job_name: 'worker'
  scrape_interval: 5s
  static_configs:
  - targets: ['192.168.2.4:3002']
- job_name: 'launcher'
  scrape_interval: 5s
  static_configs:
  - targets: ['192.168.2.4:3001']