/*
 * This file was generated by the Gradle 'init' task.
 */

import io.infinitic.loadTester.Libs

plugins { id("io.infinitic.loadTester.kotlin-library-conventions") }

dependencies {
  implementation(Libs.Infinitic.pulsar)
  implementation(Libs.Infinitic.client)
  implementation(Libs.Coroutines.core)
  implementation(Libs.MicroMeter.prometheus)

  api(project(":config"))
  api(project(":workflow"))
}
