/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.infinitic.loadTester.launcher

import io.infinitic.clients.InfiniticClient
import io.infinitic.loadTester.config.LauncherConfig

class Launcher(val client: InfiniticClient) {
    fun run(config: LauncherConfig) {
        val w = client.newWorkflow(config.workflow.klass)
//        w.async
    }
}
