/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
  // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
  id("org.jetbrains.kotlin.jvm")
}

repositories {
  // Use MavenCentral for resolving dependencies.
  mavenCentral()
}

object Libs {
  object Infinitic {
    private const val version = "0.6.0"
    const val pulsar = "io.infinitic:infinitic-pulsar:$version"
  }
  object MicroMeter {
    const val prometheus = "io.micrometer:micrometer-registry-prometheus:1.6.+"
  }
}

dependencies {
  constraints {
    // Define dependency versions as constraints
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
  }

  // Align versions of all Kotlin components
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
  implementation(Libs.Infinitic.pulsar)
  // Use the Kotlin JDK 8 standard library.
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

  // Align versions of all Kotlin components
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

  // Use JUnit Jupiter API for testing.
  testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

  // Use JUnit Jupiter Engine for testing.
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

tasks.test {
  // Use junit platform for unit tests.
  useJUnitPlatform()
}
